### ISSUE TITLE
Python flask framework

### ISSUE THREAD

**Issue by markmacgillivray** [CottageLabs/webber_server#1]
Pull any useful bits from python flask projects of old. Don't use the full octopus - too much of it is unnecessary for this project. But copy useful parts out if necessary

**Comment by markmacgillivray** [comment]
For a nice simple framework repo that probably covers a lot of the basics that we will need, see the JPER store code:

https://github.com/jiscper/store

although for now we will just be saving incoming info into an elasticsearch index, we will also be saving content into hadoop, so a simple layer to save to hadoop will come later and be added to the API endpoint functions.

For a good default index mapping, use this:

http://static.cottagelabs.com/mapping.json

**Comment by markmacgillivray** [comment]
There is an elasticsearch dao that is simple but complete enough for metadata indexing in our cottage labs portality repo, named dao.py. This is probably a good start for the elasticsearch dao, abstracting it out into simple models of the index types required, all of which can probably use the default dynamic mapping linked to above. We will then also need a dao for managing files on disk (pretty much what the previously linked jper store service does, and could just be modularised), and then also a dao for managing content in hadoop. Later we will explore the benefits of hadoop over disk storage, and estimate storage size requirements.

**Comment by anusharanganathan** [comment]
I have a basic flask app with the mapping for ES. I will extend the dao for managing files on disk, when we get to adding that functionality.
