### ISSUE TITLE
User auth

### ISSUE THREAD

**Issue by markmacgillivray** [CottageLabs/webber_server#2]
Backend server must have an API endpoint that allows an admin to provide an email address and receive an uuid in return. This creates an account on the backend for that uuid but does NOT store the email address (matching email addresses to uuid is to be handled separately). All the account needs, to begin with, is a uuid for an account ID and another one as an API key. These can then be given manually to the volunteer that installs the plugin, and they will set their user ID and api key when they first install, so subsequent plugin requests to the backend will be authenticated by checks to the accounts index.

**Comment by anusharanganathan** [comment]
@markmacgillivray 
Okay, just so I understand
```
PUT /user arg: email_id
Check current_user is authorized (current_user is Admin) if not return 403
mint uuid
Create user account for that uuid 
return: uuid
```

For creating the user Id, can I use http://accounts.cottagelabs.com/. I am a little unsure about how to integrate this. I need to read more about this (refer back to the emails you have previously sent).

"All the account needs, to begin with, is a uuid for an account ID and another one as an API key. "
> Looks like you are referring to the account API here. 
> Does this mean I mint two uuids for creating the user account - one for id, and the other for API key?  If so, do I not have to return both to the user? or have another endpoint to return the api key associated with the user

**Comment by markmacgillivray** [comment]
No, don't use accounts.cottagelabs.com. This is a standalone system, not one that will run off any of our systems. Hold off on doing this today, I will send an email update in the afternoon and put a skeleton of what we need in place here for you to follow.

**Comment by anusharanganathan** [comment]
Okay, for now I created a PUT method at  ```/register``` which will receive an email_id and return user_id and app_key. The user_id and app_key is indexed in ES. Both the user_id and app_key are uuids. 

I also created a simple decorator which expects the argument ```key``` to be sent with every method that needs to be authenticated and then queries ES to make sure this api key exists.

I can extend this to
  * Assign admin role to some keys and add decorator to make sure user is admin (for methods that need this).
  * Associate api keys to ip addresses, if we want to make the auth stonger.

**Comment by markmacgillivray** [comment]
Can you make it so that the user ID that is generated is a one-way hash of the email that is provided? So, when someone tries to create a new account by sending us an email address, do the one-way hash and check to see if we already have an account with that ID. If so, refuse the creation and respond with a message saying the account already exists. Otherwise create the new account and return the user ID and api key, as you already have.

Also, note that for the API to work, it will not necessarily only be functioning from form data - it seems when I looked at the code last night you were checking request.form for incoming variables, but more than likely the data is actually going to come in request.json. We may do a UI that would send a form, but it has to work as just an actual API first, not as a backend to a UI. So please add checks to look for incoming data in either request.json or request.form wherever necessary.

Finally, when your auth method checks for "key", where does it check? Is it going to check in the request headers, or in the request form, or in the request json, or in the request parameters? Can you make it check all of them? Or at least the headers and the json, and preferably the parameters too? Form is perhaps not necessary for this part.

**Comment by markmacgillivray** [comment]
Additionally, generation of user ID by onw-way hash from email address will also require a secret "salt". Plus, it will have to be a configurable option - it could be useful, but could also make it slightly less secure (if the salt code is ever discovered). So they may not want to use that functionality, even though it could help with user account clashes. So, please make it a configurable option, and have a configurable salt code used in the one-way hash algorithm too. Python has built-ins for hashing passwords, so you should not have to write much to implement this.

**Comment by anusharanganathan** [comment]
Yes - I was planning to do the same. These are the notes I wrote for myself

Recommendations taken from [python hashlib documentation](https://docs.python.org/2/library/hashlib.html)
100,000 rounds of SHA-256
salt should be about 16 bytes preferable from a source like os.urandom()

[Flask Hashing library](http://flask-hashing.readthedocs.org/en/latest/)
```
# settings.py
HASHING_SALT = 16 byte string generated using os.random (generate it from the console and copy)
HASHING_METHOD = 'SHA-256'
HASHING_ROUNDS = 100000
```
```
# core.py
from flask.ext.hashing import Hashing
hashing = Hashing()
# app = create_app() # FLASH APP is created in core.py
hashing.init_app(app)
```

```
from webber.core import hashing
email_hash = hashing.hash_value(email_id, salt=app.config["HASHING_SALT"])
```

*  check hash against ES and return 409 Conflict 'Email already registered'
* otherwise create resource and return a 201

__NOTE should change salt for production and not commit it__

**Comment by anusharanganathan** [comment]
Regarding request.form - I tested sending requests from the command line with CURL and the python console and the requests parameters seem to get saved in request.form. I don't think it means the request has to be sent with http form encoding. In fact all of the methods have been designed assuming JSON response needed by the http request. I did not see a requests.json in the docs, but I could have just missed it. Anyway, I will coordinate with Steve and make sure it works.

**Comment by markmacgillivray** [comment]
Have you tried CURL whilst setting the -H "content-type:application/json"? The plugin should send actual identified JSON content in this way, and any other system using the API should also do so (and the docs should specify it). I don't know if this would automatically get translated into request.form by flask, but perhaps as you are using the flask-restful package it handles this automatically. If not though, then do a check for request.json too.

**Comment by anusharanganathan** [comment]
About checking the api key - for now I check the key in either the request parameters or request form. Like I said, if requests.json is how it is going to be processed, I will add that. It's easy. As for request headers, I looked and didn't know which header will be used. So, if Steve is going to use the request headers or if there is a standard request header, I will check against that too. The way I have written this, I just need to update one method.

**Comment by anusharanganathan** [comment]
I will test again with the content type specified and make sure the methods work. Adding requests.json to the methods isn't a big job.

**Comment by markmacgillivray** [comment]
Yes, checking for a header would be useful too - expecting it in the form or the json can cause problems for people coding against the API and accidentally putting their key in with the data, and exposing it in unforeseen ways. For which header to check, just check for a header with the same name as what you are checking for elsewhere - I would normally use "apikey" but if you are already using "key" then that could be OK. If you need to be standards-compliant in header names then use x-key or x-apikey.

**Comment by anusharanganathan** [comment]
I think I will use x-apikey and also change the accepted param name to apikey. Seems more obvious.

**Comment by anusharanganathan** [comment]
commit: 0c3076a4f3a36fb2bda3b6eb63c806ee08a22dab
  * Check for api key in header, argument or data
  * Read data from requests.json, requests.form and requests.args
  * Create hash from email for user_id
