### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by markmacgillivray** [CottageLabs/webber_server#3]
Any action performed via the API (which is the only way to interact with the system and any subsequent UI will rely upon it) must be logged in a log index. So a wrapper as a python decorator around any API endpoint to log the details into a logging index should be the most straightforward approach. Store the request method, content, and result

**Comment by anusharanganathan** [comment]
Wrote a decorator to be called after each request which logs the request along with the response. 
  * I combined the arguments passed in through the url with the arguments sent in the form field into a single field called arguments
  * The url recorded also contains the server end point (for example: http://localhost:5004), which I could strip out
  * I created a setting in the config file called PRIVATE_ARGS to avoid indexing certain arguments (for example email_id sent to register method which should not be saved)

Commit: https://github.com/CottageLabs/webber_server/commit/ad1e7b199734e0ca7649fb71f79fae2b856936cc

**Comment by anusharanganathan** [comment]
@markmacgillivray though I closed this issue, just want to bring the above question to your attention

**Comment by markmacgillivray** [comment]
We will probably not need all of them, but keep it this way for now. You could add a config option called UNNECESSARY_ARGS (or NECESSARY_ARGS, depending which is easier to maintain) then we can see what info we get in there and to begin with that would be useful to review. Then we can restrict it to what is actually useful long term, to keep the data size reasonable.

**Comment by anusharanganathan** [comment]
I already do have a config option called PRIVATE_ARGS which essentially does the same thing (I had exclude writing the email id to ES). I could add other others to the same one and could rename the config option to something more appropriate down the road, depending on usage.
