### ISSUE TITLE
Receive logging

### ISSUE THREAD

**Issue by markmacgillivray** [CottageLabs/webber_server#4]
It may also be useful to be able to receive copies of logs from the browser plugins, so create an API endpoint where logs can be POSTed from the plugin. Assume that the plugin will POST either one JSON object representing one log, or a list of JSON objects for multiple logs, and assume the browser plugin keeps note of which ones it has sent - so the backend just stores them, and records which user ID submitted them. Save these in a separate logging index from the one storing the backend logs themselves.

**Comment by anusharanganathan** [comment]
commit: https://github.com/CottageLabs/webber_server/commit/19a50cbd1428d71bf16c1f6cd01879befd61d5db

I add each log message to a property called log in ES.
