### ISSUE TITLE
Receive visit notifications

### ISSUE THREAD

**Issue by markmacgillivray** [CottageLabs/webber_server#5]
Must be able to receive POSTs from the plugin, to something like:

webber.cottagelabs.com/visit

containing something like:

{
  url: "http://cottagelabs.com/whatever"
}

Save them in a visits index, and ensure that the user that POSTs them is authenticated, and record which user POSTed them, so the saved index data may end up like:

{
  created_date: "blah",
  author: "userId of authenticated user",
  visit: {
    url: "http://cottagelabs.com/whatever"
  }
}

**Comment by anusharanganathan** [comment]
commit: https://github.com/CottageLabs/webber_server/commit/8eccb5c38a9e1f085df6f1eb526cbf2fef3919b6
